# Generated by Django 4.2 on 2024-01-22 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('columns', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('database_name', models.CharField(max_length=255, unique=True)),
                ('server_ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterDatabaseSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('schema', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenesysAuthenticator.masterdatabase')),
            ],
            options={
                'verbose_name': 'Database Schema',
                'verbose_name_plural': 'Database Schemas',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Senior Vice President - Projects', 'Senior Vice President - Projects'), ('Vice President', 'Vice President'), ('General Manager Projects', 'General Manager Projects'), ('Senior Project Manager', 'Senior Project Manager'), ('Program Manager', 'Program Manager'), ('Manager', 'Manager'), ('Deputy General Manager', 'Deputy General Manager'), ('Assistant Project Manager', 'Assistant Project Manager'), ('Team Manager', 'Team Manager'), ('Team Leader', 'Team Leader'), ('Assistant Team Leader', 'Assistant Team Leader'), ('Senior Executive', 'Senior Executive'), ('Executive', 'Executive'), ('Trainee', 'Trainee')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('has_resigned', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('selected_databases', models.ManyToManyField(to='GenesysAuthenticator.masterdatabase')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchemaAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('has_access', models.BooleanField(default=False)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenesysAuthenticator.masterdatabase')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenesysAuthenticator.masterdatabaseschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivilegeFunctionValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('privilege_function_validation', models.BooleanField(default=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenesysAuthenticator.masterdatabase')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_privileges', to=settings.AUTH_USER_MODEL)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenesysAuthenticator.masterdatabaseschema')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GenesysAuthenticator.databasetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='databasetable',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenesysAuthenticator.masterdatabase'),
        ),
        migrations.AddField(
            model_name='databasetable',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenesysAuthenticator.masterdatabaseschema'),
        ),
        migrations.CreateModel(
            name='DatabasePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('db_access', models.BooleanField(default=False)),
                ('privilege_select', models.BooleanField(default=False)),
                ('privilege_insert', models.BooleanField(default=False)),
                ('privilege_update', models.BooleanField(default=False)),
                ('privilege_delete', models.BooleanField(default=False)),
                ('privilege_sequence', models.BooleanField(default=False)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GenesysAuthenticator.masterdatabase')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_given', to=settings.AUTH_USER_MODEL)),
                ('schemas', models.ManyToManyField(to='GenesysAuthenticator.masterdatabaseschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('databases', models.ManyToManyField(to='GenesysAuthenticator.masterdatabase')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
