# Generated by Django 4.2 on 2024-01-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenesysAuthenticator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegefunctionvalidation',
            name='columns',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
