# Generated by Django 4.2 on 2024-01-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('database_name', models.CharField(max_length=255, unique=True)),
                ('server_ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('emp_id', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('designation', models.CharField(choices=[('Senior Vice President - Projects', 'Senior Vice President - Projects'), ('Vice President', 'Vice President'), ('General Manager Projects', 'General Manager Projects'), ('Senior Project Manager', 'Senior Project Manager'), ('Program Manager', 'Program Manager'), ('Manager', 'Manager'), ('Deputy General Manager', 'Deputy General Manager'), ('Assistant Project Manager', 'Assistant Project Manager'), ('Team Manager', 'Team Manager'), ('Team Leader', 'Team Leader'), ('Assistant Team Leader', 'Assistant Team Leader'), ('Senior Executive', 'Senior Executive'), ('Executive', 'Executive'), ('Trainee', 'Trainee')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('has_resigned', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('selected_databases', models.ManyToManyField(to='GenesysUserApp.masterdatabase')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
